config:
  target: "http://localhost:3000"
  processor: ./helper.js
  phases:
    - duration: 60
      arrivalRate: 10
      name: Warm up
    - duration: 600
      arrivalRate: 150
      name: Main

scenarios:
  - name: "Search flights"
    flow:
      - get:
          url: /destinations
          capture:
            - json: "$"
              as: "destinations"
      - function: setRandomDestination
      - think: 1
      - get:
          url: /flights
          qs:
            from: "{{ flightFrom }}"
      - get:
          url: /flights
          qs:
            to: "{{ flightTo }}"
  - name: "Book flight"
    flow:
      - get:
          url: "/flights"
          capture:
            - json: "$"
              as: "flights"
      - function: setRandomFlightId
      - get:
          url: "/flights/{{ flightId }}/seats"
          capture:
            - json: "$"
              as: "seats"
      - function: setBookingRequest
      - think: 3
      - post:
          url: "/bookings"
          json: "{{ bookingRequest }}"
          auth:
            user: user
            pass: pw
