version: '3.3'

services:
  k6-instance-1:
    build: ./k6
    environment:
      - TARGET=${SUT_IP}:${SERVICE_PORT_1}
      - TIMESTAMP=${TIMESTAMP}
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - ./k6:/usr/src/app/k6  
    entrypoint: ["k6", "run", "/usr/src/app/k6/script.js"]
    command: 
      - -e
      - target=${SUT_IP}:${SERVICE_PORT_1}
      - --out
      - csv=/usr/src/app/k6/client_results_${SERVICE_PORT_1}.csv
      - --summary-export
      - /usr/src/app/k6/client_summary_${SERVICE_PORT_1}.json
    deploy:
      resources:
        limits:
          cpus: '1.5'  
    networks:
      - k6-network

  k6-instance-2:
    build: ./k6
    environment:
      - TARGET=${SUT_IP}:${SERVICE_PORT_2}
      - TIMESTAMP=${TIMESTAMP}
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - ./k6:/usr/src/app/k6  
    entrypoint: ["k6", "run", "/usr/src/app/k6/script.js"]
    command: 
      - -e
      - target=${SUT_IP}:${SERVICE_PORT_2}
      - --out
      - csv=/usr/src/app/k6/client_results_${SERVICE_PORT_2}.csv
      - --summary-export
      - /usr/src/app/k6/client_summary_${SERVICE_PORT_2}.json
    deploy:
      resources:
        limits:
          cpus: '1.5' 
    networks:
      - k6-network

networks:
  k6-network:
    driver: bridge
