version: '3.3'

services:
  core0:
    build:
      context: .
    ports:
      - "3000:3000"
    command: ["./cmd/flight-booking-service/flight-booking-service", "--port", "3000"]
    deploy:
      resources:
        limits:
          cpus: '1.5'
        reservations:
          cpus: '1.0'

  core1:
    build:
      context: .
    ports:
      - "3001:3001"
    command: ["./cmd/flight-booking-service/flight-booking-service", "--port", "3001"]
    deploy:
      resources:
        limits:
          cpus: '1.5'
        reservations:
          cpus: '1.0'
